# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rack-oauth}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["remi"]
  s.date = %q{2009-11-02}
  s.description = %q{Rack Middleware for OAuth Authorization}
  s.email = %q{remi@remitaylor.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
     "Rakefile",
     "VERSION",
     "examples/rails-example/README",
     "examples/rails-example/Rakefile",
     "examples/rails-example/app/controllers/application_controller.rb",
     "examples/rails-example/app/controllers/welcome_controller.rb",
     "examples/rails-example/app/helpers/application_helper.rb",
     "examples/rails-example/app/helpers/welcome_helper.rb",
     "examples/rails-example/app/views/welcome/index.html.erb",
     "examples/rails-example/config/boot.rb",
     "examples/rails-example/config/database.yml",
     "examples/rails-example/config/environment.rb",
     "examples/rails-example/config/environments/development.rb",
     "examples/rails-example/config/environments/production.rb",
     "examples/rails-example/config/environments/test.rb",
     "examples/rails-example/config/initializers/backtrace_silencers.rb",
     "examples/rails-example/config/initializers/inflections.rb",
     "examples/rails-example/config/initializers/mime_types.rb",
     "examples/rails-example/config/initializers/new_rails_defaults.rb",
     "examples/rails-example/config/initializers/session_store.rb",
     "examples/rails-example/config/locales/en.yml",
     "examples/rails-example/config/routes.rb",
     "examples/rails-example/db/development.sqlite3",
     "examples/rails-example/db/seeds.rb",
     "examples/rails-example/db/test.sqlite3",
     "examples/rails-example/doc/README_FOR_APP",
     "examples/rails-example/lib/tasks/rspec.rake",
     "examples/rails-example/log/development.log",
     "examples/rails-example/log/production.log",
     "examples/rails-example/log/server.log",
     "examples/rails-example/log/test.log",
     "examples/rails-example/public/404.html",
     "examples/rails-example/public/422.html",
     "examples/rails-example/public/500.html",
     "examples/rails-example/public/favicon.ico",
     "examples/rails-example/public/images/rails.png",
     "examples/rails-example/public/javascripts/application.js",
     "examples/rails-example/public/javascripts/controls.js",
     "examples/rails-example/public/javascripts/dragdrop.js",
     "examples/rails-example/public/javascripts/effects.js",
     "examples/rails-example/public/javascripts/prototype.js",
     "examples/rails-example/public/robots.txt",
     "examples/rails-example/script/about",
     "examples/rails-example/script/autospec",
     "examples/rails-example/script/console",
     "examples/rails-example/script/dbconsole",
     "examples/rails-example/script/destroy",
     "examples/rails-example/script/generate",
     "examples/rails-example/script/performance/benchmarker",
     "examples/rails-example/script/performance/profiler",
     "examples/rails-example/script/plugin",
     "examples/rails-example/script/runner",
     "examples/rails-example/script/server",
     "examples/rails-example/script/spec",
     "examples/rails-example/script/spec_server",
     "examples/rails-example/spec/integration/login_spec.rb",
     "examples/rails-example/spec/rcov.opts",
     "examples/rails-example/spec/spec.opts",
     "examples/rails-example/spec/spec_helper.rb",
     "examples/rails-example/tmp/webrat-1257205170.html",
     "examples/rails-example/tmp/webrat-1257205276.html",
     "examples/rails-example/tmp/webrat-1257205315.html",
     "examples/rails-example/tmp/webrat-1257205333.html",
     "examples/rails-example/tmp/webrat-1257205380.html",
     "examples/rails-example/tmp/webrat-1257205757.html",
     "examples/rails-example/tmp/webrat-1257210107.html",
     "examples/rails-example/tmp/webrat-1257210160.html",
     "examples/rails-example/tmp/webrat-1257210488.html",
     "examples/rails-example/tmp/webrat-1257210501.html",
     "examples/rails-example/tmp/webrat-1257210545.html",
     "examples/rails-example/tmp/webrat-1257210564.html",
     "examples/rails-example/tmp/webrat-1257210581.html",
     "examples/rails-example/tmp/webrat-1257210600.html",
     "examples/rails-example/tmp/webrat-1257210608.html",
     "examples/sinatra-twitter.rb",
     "examples/sinatra-twitter.ru",
     "lib/rack-oauth.rb",
     "lib/rack/oauth.rb",
     "spec/data/authorized_access_token.yml",
     "spec/data/authorized_oauth_verifier.yml",
     "spec/data/authorized_request_secret.yml",
     "spec/data/authorized_request_token.yml",
     "spec/data/unauthorized_request_token.yml",
     "spec/rack_oauth_middleware_spec.rb",
     "spec/sample_sinatra_app_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/remi/rack-oauth}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Rack Middleware for OAuth Authorization}
  s.test_files = [
    "spec/rack_oauth_middleware_spec.rb",
     "spec/spec_helper.rb",
     "spec/sample_sinatra_app_spec.rb",
     "examples/sinatra-twitter.rb",
     "examples/rails-example/spec/integration/login_spec.rb",
     "examples/rails-example/spec/spec_helper.rb",
     "examples/rails-example/config/boot.rb",
     "examples/rails-example/config/routes.rb",
     "examples/rails-example/config/environments/development.rb",
     "examples/rails-example/config/environments/test.rb",
     "examples/rails-example/config/environments/production.rb",
     "examples/rails-example/config/environment.rb",
     "examples/rails-example/config/initializers/backtrace_silencers.rb",
     "examples/rails-example/config/initializers/inflections.rb",
     "examples/rails-example/config/initializers/new_rails_defaults.rb",
     "examples/rails-example/config/initializers/session_store.rb",
     "examples/rails-example/config/initializers/mime_types.rb",
     "examples/rails-example/db/seeds.rb",
     "examples/rails-example/app/helpers/application_helper.rb",
     "examples/rails-example/app/helpers/welcome_helper.rb",
     "examples/rails-example/app/controllers/application_controller.rb",
     "examples/rails-example/app/controllers/welcome_controller.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

